version: "3.9"
services:
  app:
    image: svhd/logto:${SOFTWARE_VERSION_TAG}
    restart: always
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "npm start"]
    ports:
      - 172.17.0.1:33267:3001
      - 172.17.0.1:55089:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/logto
      - ENDPOINT=https://${DOMAIN}
      - ADMIN_ENDPOINT=https://${DOMAIN}:8504
      - NODE_ENV=production
  postgres:
    image: elestio/postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: logto
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 172.17.0.1:27115:5432

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:51032:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
